services:
  - docker

env:
  global:
    - DOCKER_ACCOUNT=sogis
    - DOCKER_REPO=oereb-web-service

branches:
  only:
    - master

script:
  - gradle -DDOCKER_ACCOUNT=$DOCKER_ACCOUNT -DDOCKER_REPO=$DOCKER_REPO buildImage
  - docker images

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && docker push $DOCKER_ACCOUNT/$DOCKER_REPO
  on:
    branch: master